package database;
// Generated 26 ene 2025, 12:58:29 by Hibernate Tools 6.5.1.Final

/**
 * Languages generated by hbm2java
 */
public class Languages implements java.io.Serializable {

	private Integer languageId;
	private String language;

	public Languages() {
	}

	public Languages(String language) {
		this.language = language;
	}

	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
