package database;
// Generated 26 ene 2025, 12:58:29 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

/**
 * RegionAreas generated by hbm2java
 */
public class RegionAreas implements java.io.Serializable {

	private String regionName;
	private BigDecimal regionArea;

	public RegionAreas() {
	}

	public RegionAreas(String regionName, BigDecimal regionArea) {
		this.regionName = regionName;
		this.regionArea = regionArea;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public BigDecimal getRegionArea() {
		return this.regionArea;
	}

	public void setRegionArea(BigDecimal regionArea) {
		this.regionArea = regionArea;
	}

}
